export const NOTEREQUEST = 'NOTEREQUEST'
export const NOTESUCCESS = 'NOTESUCCESS'
export const NOTEFAIL = 'NOTEFAIL'


export const CREATEREQUEST = 'CREATEREQUEST'
export const CREATESUCCESS = 'CREATESUCCESS'
export const CREATEFAIL = 'CREATEFAIL'


export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'
export const USER_SIGNOUT = 'USER_SIGNOUT'




export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'